language: objective-c
osx_image: xcode9.4
install:
  - date
script:
  - date

deploy:
  provider: pages
  fqdn: timm.preetz.name
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: 
  on:
    branch: master